backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
    - name: pages
      label: Pages
      files:
        - file: "src/pages/index.md"
          label: Landing Page
          name: index
          fields:
            - {label: Template Key, name: templateKey, widget: hidden, default: index-page}
            - {label: Title, name: title, widget: string}
            - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
            - {label: Image, name: image, widget: object, fields: [{label: Src, name: src, widget: image}, {label: Alt, name: alt, widget: string}]}
            - {label: Body, name: body, widget: markdown}